### ISSUE TITLE
LICENSE file is missing on pypi

### ISSUE THREAD

**Issue by tigerfoot** [pallets-eco/flask-principal#46]
To help packaging, especially legal review, it would be nice to have the LICENSE file included in pypi distribution.

**Comment by Abdur-rahmaanJ** [comment]
@tigerfoot Thanks the the issue, we added it in the revamp, should be up when we push the next release

**Comment by Abdur-rahmaanJ** [comment]
![Selection_357](https://github.com/pallets-eco/flask-principal/assets/22630684/d43d860a-d3bd-47b4-82ae-49615eb470d5)

Closing as the license is stated on Pypi and the new license.txt will be included in future releases.
