### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by rustanacexd** [pallets-eco/flask-principal#50]
just curious

**Comment by qq850482461** [comment]
maybe

**Comment by hardy4yooz** [comment]
oh no!

**Comment by born2discover** [comment]
Considering that latest commit dates back to 26 May 2015 and that there are 6 un-merged pull requests with oldest one being from 2013... I guess it sadly is dead.

@mattupstate Can you please confirm or deny it please?

**Comment by leonprou** [comment]
I started using all the Flask Security stack, now I see it's pretty abounded. Is there any alternatives?

**Comment by patvdleer** [comment]
This seems to be the only package to provide object based/row level permissions, as far as I know Flask Security doesn't do that

**Comment by leonprou** [comment]
@patvdleer Flask Security based on Flask Principal. Both repos also owned by the same person.

**Comment by patvdleer** [comment]
@leonprou Flask security does provide role based permissions but these are access based as far, as I know, not object based/row level based

**Comment by bellomatt** [comment]
I am using this project in a online erp system with a lot cusomize. 
In my experience this project is not "dead". As a base lib this is perfect, no fancy useless function, and stable as hell.
The philosophy in this project is awesome！

**Comment by williamjmorenor** [comment]
> I am using this project in a online erp system with a lot customize.
> In my experience this project is not "dead". As a base lib this is perfect, no fancy useless function, and stable as hell.
> The philosophy in this project is awesome！

Just curios is your project open source?

**Comment by leecbaker** [comment]
Definitely looks like the project is dead. According to his profile, the owner hasn't made any flask-related contributions since 2015, and looks like he doesn't do anything on Github at all any more.

Any interest in somebody else supporting the project? Seems like it should be relatively low effort, since few changes should be needed.

**Comment by HeyITGuyFixIt** [comment]
Here's a [blog post](https://mattupstate.com/blog/my-time-in-open-source-a-memoir) from mattupstate that explains what has happened.

**Comment by israel-oye** [comment]
Wow. Sometimes we forget that we're human first before being considered software developers.

**Comment by Abdur-rahmaanJ** [comment]
Hi all folks, Flask-principal is now maintained by the Pallets-eco organization. Thanks for your support and concern for all those years.

@aenglander Marked for closing.
