### ISSUE TITLE
use mongoengine

### ISSUE THREAD

**Issue by ilaer** [pallets-eco/flask-principal#54]
principal is very good.
i do`t know how to use principal use mongodb.
can you update you doc,give a demo about mongoengine and principal?
thk.

**Comment by Abdur-rahmaanJ** [comment]
Hi :wave: Thanks for your concern. If you need help using Mongodb and Flask-principal, please consider asking for help on the [Pallets Discord](https://discord.com/invite/pallets). Thanks.
