### ISSUE TITLE
Strange symlink? submodule? in docs - preventing pip install of main

### ISSUE THREAD

**Issue by jwag956** [pallets-eco/flask-principal#86]
I am trying to test against the 'main' branch - with the new changes (BTW - thank you for resurrecting this package).

Trying: pip install git+https://github.com/pallets-eco/flask-principal@main#egg=flask-principal
and after a bit - it times out:

```
fatal: clone of 'git://github.com/mitsuhiko/flask-sphinx-themes.git' into submodule path '/private/var/folders/tp/8sq0p0ld5_zfd8p8xywyyrfw0000gn/T/pip-install-ddhmpqtd/flask-principal_925399e419434c55b0786ccc75d81ed1/docs/_themes' failed
  Failed to clone 'docs/_themes'. Retry scheduled
  fatal: unable to connect to github.com:
  github.com[0: 140.82.116.4]: errno=Operation timed out

  fatal: clone of 'git://github.com/mitsuhiko/flask-sphinx-themes.git' into submodule path '/private/var/folders/tp/8sq0p0ld5_zfd8p8xywyyrfw0000gn/T/pip-install-ddhmpqtd/flask-principal_925399e419434c55b0786ccc75d81ed1/docs/_themes' failed
  Failed to clone 'docs/_themes' a second time, aborting
```

I have never seen this - but the docs directory seems to have a symlink or a sub-module? to another github repo (which is no longer in use). I believe the more 'modern' way of handling this is using requirements.

**Comment by Abdur-rahmaanJ** [comment]
lol so strange let me sort this out

**Comment by Abdur-rahmaanJ** [comment]
confirmed, will fix

**Comment by Abdur-rahmaanJ** [comment]
@jwag956 Fixed in #89 , confirm if you still get it with `pip install git+https://github.com/pallets-eco/flask-principal@main `

**Comment by jwag956** [comment]
fixed - thanks - and all my flask_security tests run correctly with latest... double great!

**Comment by Abdur-rahmaanJ** [comment]
Cool, original author was also pretty good!
